export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESSFUL';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_USER_SIGN_IN = 'AUTH_USER_SIGN_IN';
export const TRANSACTION_LIST = 'TRANSACTION_LIST';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const CHANGE_CREDIT = 'CHANGE_CREDIT'
